### ISSUE TITLE
The title is "Play" when I launch a movie with Pulsar from the Arch Interface

### ISSUE THREAD

**Issue by NerosTie** [abricot/webinterface.arch#8]
On the last version of Kodi (OSMC), if I launch a movie from the web interface (Arch 2) with Pulsar as the external video add-on, the title is "Play" and there is no information about the movie (in Kore for example). **It's harder to add subtitles with this kind of issue.**

![arch_kodi](https://cloud.githubusercontent.com/assets/4572452/11897398/b3e51832-a58f-11e5-98d5-d5147e34e302.png)
![screenshot_2015-12-18-14-11-34_org xbmc kore](https://cloud.githubusercontent.com/assets/4572452/11897728/62a499e0-a592-11e5-9422-644a0928c251.png)

BUT. If I launch the movie from the Kodi interface in Pulsar, there is no issue in Arch:

![arch_kodi1](https://cloud.githubusercontent.com/assets/4572452/11897492/73a0fe34-a590-11e5-8ff6-f253a7e8cf37.png)
![screenshot_2015-12-18-14-17-11_org xbmc kore](https://cloud.githubusercontent.com/assets/4572452/11897731/68aa3840-a592-11e5-8f86-bb4ee72544b8.png)

Few months ago with Arch1 and an older version of Kodi, this bug didn't exist.

**Comment by nicolasabric** [comment]
@NerosTie I m afraid there is nothing I can do at Arch level. I add a look at the pulsar repo on Github and turns out that this issue was already reported there (see https://github.com/steeve/plugin.video.pulsar/issues/190). Unfortunately there is no pulsar release, yet, that contains this fix (Pull request has yet to be accepted). From there you have two options : 
- Comment the issue on pulsar repo and hope it will accelerate stuff,
- Or the nerdy way clone the pulsar repo and create your own custom build of it containing the fix in PR190.

Happy season holidays

**Comment by NerosTie** [comment]
So this is an issue from Pulsar and there is a fix... Well, time to be nerdy!   

Thanks! And happy season holidays too 🎅🎄
